# Generated by Django 5.1.6 on 2025-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=100)),
                ('full_time_remote', models.CharField(max_length=100)),
                ('job_details', models.TextField()),
            ],
        ),
    ]
